### ISSUE TITLE
Fix the stacked links

### ISSUE THREAD

**Issue by j127** [codeselfstudy/search_engine_show_me_urls#2]
Only the main link should show the URL. The smaller links at the bottom shouldn't.

![image](https://user-images.githubusercontent.com/96479/72769833-f17ceb00-3bb0-11ea-87ca-90c5ab4de9cc.png)

**Comment by datadaveshin** [comment]
I think I got it fixed, but only tested in Firefox:

![removed-stacked-links](https://user-images.githubusercontent.com/14435667/73591470-a497ef00-44a3-11ea-856b-884dcf4f71bf.png)

**Comment by j127** [comment]
Looks good. If you make a pull request, we can merge it.

**Comment by datadaveshin** [comment]
Put in PR

**Comment by j127** [comment]
I fixed one more bug, built it as version 0.1.6, and submitted it to Mozilla and Google. The extension has about 40 downloads so far. It should auto-download to browsers as soon as the new version gets approved.
